### ISSUE TITLE
package export ist broken in php8

### ISSUE THREAD

**Issue by fwoldt** [netgen/ezpublish-legacy#7]
Create a new package for example content object export

and do all steps until export to file

=> this is broken

-  vendor/zetacomponents/archive/src/file/block_file.php
   sizeof(): Argument #1 ($value) must be of type Countable|array, string given in vendor/zetacomponents/archive/src/file/block_file.php on line 366
  @see https://github.com/zetacomponents/Archive/commit/9e1fa02aabfd1ffacde4e289064ccd2fb8c01d32

  => zetacomponents version master has the bugfix already but the current stable version 1.5 not

  => so we have to patch => or switch to master of zetacomponents in ezpbublish_legacy composer.json
     https://github.com/ezsystems/ezpublish-legacy/blob/2019.03/composer.json

**Comment by emodric** [comment]
zetacomponents/archive is tagged with 1.5.1 thanks to @derickr so this is fixed now.

**Comment by fwoldt** [comment]
yes the export is working now :-)
